name: statecraft
description: Elegant state handling for Flutter and flutter_bloc. Build smooth async, form, list, and paginated states with ease.
version: 0.1.1
repository: https://github.com/plokmij/statecraft

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - state-management
  - flutter
  - bloc
  - cubit

screenshots:
  - description: The statecraft package logo.
    path: screenshots/logo.png
